version: '3.3'

services:
    mysqldb:
        image: mysql:5.7
        user: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: SchoolRegistrationSystem
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"

    app:
        depends_on:
            - mysqldb
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
